current_version = "1.2.4"
commit = true
tag = true

[files."Cargo.toml"]
search = "version = \"{current_version}\"$"
replace = "version = \"{new_version}\""

[files.VERSION]
search = "{current_version}"
replace = "{new_version}"
