name: Run tests

env:
  CARGO_TERM_COLOR: always

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # selecting a toolchain either by action or manual `rustup` calls should happen
        # before the plugin, as the cache uses the current rustc version as its cache key
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings

      - name: Prepare tests
        run : |
          git config --global user.email "test@fulljoin.nl"
          git config --global user.name "Github Actions tester"

      - name: Test
        run: cargo test
